recipe: default.v1
assistant_id: 20230303-143719-chunky-apple
language: en
pipeline:
- name: WhitespaceTokenizer
  token_pattern: (?u)\b\w+\b
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
  OOV_token: oov
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 200
  ranking_length: 5
- name: DucklingEntityExtractor
  url: http://localhost:8000
  dimensions:
  - email
  - number
  - amount-of-money
- name: EntitySynonymMapper
- name: ResponseSelector
  retrieval_intent: out_of_scope
  scale_loss: false
  epochs: 100
- name: ResponseSelector
  retrieval_intent: faq
  scale_loss: false
  epochs: 100
- name: ResponseSelector
  retrieval_intent: chitchat
  scale_loss: false
  epochs: 100
#- name: FallbackClassifier
#  threshold: 0.7
policies:
- name: MappingPolicy
- name: RulePolicy
  core_fallback_threshold: 0.7
  nlu_threshold: 0.7
  core_threshold: 0.7
  core_fallback_action_name: action_default_fallback
  enable_fallback_prediction: true
  max_history: 6
  epochs: 100
- name: AugmentedMemoizationPolicy
- name: TEDPolicy
  max_history: 10
  epochs: 100
  batch_size:
  - 32
  - 64
